config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :users, only: %i(index show)
  resources :reactions, only: %i(create)
  resources :matching, only: %i(index)
  resources :chat, only: %i(create show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_messages
  has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"
  enum status: { like: 0, dislike: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chat_messages
  has_many :chat_room_users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum sex: { 男: 0, 女: 1 }

  mount_uploader :img_name, ImgNameUploader

  validates :img_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(name self_introduction sex img_name))
    devise_parameter_sanitizer.permit(:account_update, keys: %i(name self_introduction sex img_name))
  end

  def after_sign_in_path_for(resource)
    users_path
  end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    # 自分の持っているチャットルームを取得
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    # 自分の持っているチャットルームからチャット相手のいるルームを探す
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    # なければ作成する
    if chat_room.blank?
      # chat_roomsテーブルにレコードを作成
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    # チャットルームへ遷移させる
    redirect_to action: :show, id: chat_room.id
  end

  def show
    # チャット相手の情報を取得する
    chat_room = ChatRoom.find_by(id: params[:id])
    @chat_room_user = chat_room.chat_room_users.
      where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: chat_room).order(:created_at)
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  
  def index
    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id)
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
  end

end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
   def create
    reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: current_user.id)
    reaction.update_attributes(
      status: params[:reaction]
    )
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/show.html.erb
<div class="chatPage">
  <header class="header">
  <%= link_to "", matching_index_path, class: "linkToMatching" %>
    <div class="chatPartner">
      <div class="chatPartner_img"><%= image_tag @chat_room_user.img_name.url(:thumb) %></div>
      <div class="chatPartner_name"><%= @chat_room_user.name %></div>
    </div>
  </header>
  <div class="container">
    <div class="messagesArea messages">
      <%= render @chat_messages %>
    </div>
  </div>
  <form class="messageInputForm">
    <div class='container'>
      <input type="text" data-behavior="room_speaker" class="messageInputForm_input" placeholder="メッセージを入力...">
    </div>
  </form>
</div>

app/views/chat_messages/_chat_message.html.erb
<div class="message">
  <span><%= chat_message.user.name %>:</span><div class="commonMessage"><div><%= chat_message.message %></div></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Match</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="current_user_id" content="<%= current_user.id if current_user %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/matching/index.html.erb
<div class="matchingPage">
  <header class="header">
    <i class="fas fa-comments fa-3x"></i>
    <div class="header_logo"><%= link_to image_tag("techpit-march-icon.png"), users_path %></div>
  </header>
  <div class="container">
    <div class="mt-5">
      <div class="matchingNum"><%= @match_users.size %>人とマッチングしています</div>
      <h2 class="pageTitle">マッチングした人一覧</h2>
      <div class="matchingList">
        <% @match_users.each do |user| %>
          <div class="matchingPerson">
          <div class="matchingPerson_img"><%= image_tag user.img_name.url(:thumb) %></div>
            <div class="matchingPerson_name"><%= user.name %></div>
	     <%= form_tag :chat_index, method: :post do %>
              <input name="user_id" type="hidden" value="<%= user.id %>" />
              <%= submit_tag 'チャットを開く', class: "chatForm_btn" %>
            <% end %>
	  </div>
        <% end %>
      </div>
    <div>
  </div>
</div>

app/views/top/index.html.erb
<div class="loginPage">
  <div class="container">
    <div class="loginPage_contents">
      <h1 class="h4 loginPage_contents_title">新しいマッチを見つけよう</h1>
      <%= link_to "メールアドレスでログインする", new_user_session_path, class: "btn loginPage_contents_btn" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="topPage">
  <nav class="nav">
    <ul>
      <li class="personIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-user'), user_path(current_user.id)) %></li>
      <li class="appIcon"><%= link_to image_tag("techpit-march-icon.png"), users_path %></li>
      <li class="messageIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-comments'), matching_index_path) %></li>
    </ul>
  </nav>
  <div id="tinderslide">
    <ul>
      <% @users.each do |user| %>
        <li data-user_id="<%= user.id %>">
          <div class="userName"><%= user.name %></div>
          <%= image_tag user.img_name.url(:thumb) %>
          <div class="like"></div>
          <div class="dislike"></div>
        </li>
      <% end %>
    </ul>
    <div class="noUser">近くにお相手がいません。</div>
  </div>
  <div class="actions" id="actionBtnArea">
      <a href="#" class="dislike"><i class="fas fa-times fa-2x"></i></a>
      <a href="#" class="like"><i class="fas fa-heart fa-2x"></i></a>
  </div>
</div>
<script>
  // スワイプするユーザー数の定数を定義
  var usersNum = <%= @users.length %>
  var currentUserIndex = 0;
  var postReaction = function (user_id, reaction) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
        }
    });
    $.ajax({
      type: "POST",
      url: "<%= reactions_path %>",
      data: {
        user_id: user_id,
        reaction: reaction,
      },
      success: function(j_data){
        console.log("success")
      }
    });
  }
  $("#tinderslide").jTinder({
    onDislike: function (item) {
      currentUserIndex++;
      checkUserNum();
      var user_id = item[0].dataset.user_id
      postReaction(user_id, 'dislike')
    },
    onLike: function (item) {
      currentUserIndex++;
      checkUserNum();
      var user_id = item[0].dataset.user_id
      postReaction(user_id, 'like')
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  $('.actions .like, .actions .dislike').click(function(e){
    e.preventDefault();
    $("#tinderslide").jTinder($(this).attr('class'));
  });

  function checkUserNum() {
    // スワイプするユーザー数とスワイプした回数が同じになればaddClassする
    if (currentUserIndex === usersNum){
      $(".noUser").addClass("is-active");
      $("#actionBtnArea").addClass("is-none")
      return;
    }
  }
</script>

app/views/users/show.html.erb
<div class='usershowPage'>
  <div class='container'>
    <header class="header">
      <p class='header_logo'>
        <%= link_to image_tag("techpit-march-icon.png"), users_path %>
      </p>
    </header>
    <div class='userInfo'>
      <div class='userInfo_img'>
        <%= image_tag @user.img_name.url(:thumb) %>
      </div>
      <div class='userInfo_name'><%= @user.name%></div>
      <div class='userInfo_selfIntroduction'><%= @user.self_introduction %></div>
    </div>
    <% if current_user.id == @user.id %>
      <div class='userAction'>
        <div class="userAction_edit userAction_common">
          <%= link_to(content_tag(:i, "", class: 'fas fa-edit fa-2x'), edit_user_registration_path) %>
          <span>情報を編集</span>
        </div>
        <div class='userAction_logout userAction_common'>
          <%= link_to(content_tag(:i, "", class: 'fas fa-cog fa-2x'), destroy_user_session_path, method: :delete) %>
          <span>ログアウト</span>
        </div>
      </div>
    <% end %>
  </div>
</div>